# @authors: Somya Arora, Arash Pourhabibi
sudo: required

branches:
  only:
    - master
    - dev

language: bash

before_install:
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sudo sh get-docker.sh
  - sudo usermod -aG docker $USER
  - mkdir -p $HOME/.docker 
  - |-
    echo "{\"experimental\": \"enabled\"}" > $HOME/.docker/config.json
  - sudo service docker restart
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --use --name host-builder --buildkitd-flags '--allow-insecure-entitlement network.host'
  - docker buildx use host-builder
  - docker buildx inspect --bootstrap

# Build Matrix :
env:
  - DH_REPO="alok123t/java_travis" IMG_TAG="latest" DF_PATH="./commons/java/openjdk11"
  #Spell Check
  - Spell_Check="1"

# Separate build for spellcheck in modified .md files and auto-updation of gh-pages branch
script:
  - if [[ -z $Spell_Check ]];
    then source ${TRAVIS_BUILD_DIR}/scripts/travis/travis.sh;
    else source ${TRAVIS_BUILD_DIR}/scripts/travis/docs.sh;
    fi
