language: ruby
rvm:
- 2.2.5

sudo: false

addons:
  apt:
    packages:
    - gsl-bin
    - libcurl4-openssl-dev # required to avoid SSL errors
    - libgsl0ldbl
    - libgsl0-dev
    - libgsl0-dbg

notifications:
  email: false
  slack: 
    parsa-epfl:jY28s7BKfln7gmNdbtxoQWx7

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

# branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages     # test the gh-pages branch
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

