# @authors: Somya Arora, Arash Pourhabibi
sudo: required

branches:
  only:
    - master
    - dev

language: bash

services:
  - docker

# Build Matrix :
env:
  # Commons
  # Java
  - DH_REPO="cloudsuite/java" IMG_TAG="openjdk7" DF_PATH="./commons/java/openjdk7"
  - DH_REPO="cloudsuite/java" IMG_TAG="openjdk8" DF_PATH="./commons/java/openjdk8" IMG_LATEST_TAG="latest"

  # Hadoop
  - DH_REPO="cloudsuite/hadoop" IMG_TAG="2.7.6" DF_PATH="./commons/hadoop/2.7.6"
  - DH_REPO="cloudsuite/hadoop" IMG_TAG="2.9.1" DF_PATH="./commons/hadoop/2.9.1" IMG_LATEST_TAG="latest" 

  # Spark
  - DH_REPO="cloudsuite/spark" IMG_TAG="1.5.1" DF_PATH="./commons/spark/1.5.1"
  - DH_REPO="cloudsuite/spark" IMG_TAG="2.1.0" DF_PATH="./commons/spark/2.1.0"
  - DH_REPO="cloudsuite/spark" IMG_TAG="2.3.1" DF_PATH="./commons/spark/2.3.1" IMG_LATEST_TAG="latest"

  # Faban
  - DH_REPO="cloudsuite/faban" IMG_TAG="1.3" DF_PATH="./commons/faban/1.3"
  - DH_REPO="cloudsuite/faban" IMG_TAG="1.4" DF_PATH="./commons/faban/1.4" IMG_LATEST_TAG="latest"

  
  # Memcached
  - DH_REPO="cloudsuite/memcached" IMG_TAG="1.5.9" DF_PATH="./commons/memcached/1.5.9" IMG_LATEST_TAG="latest"

  # Datasets
  # Movielens
  - DH_REPO="cloudsuite/movielens-dataset" IMG_TAG="latest" DF_PATH="./datasets/movielens-dataset"
  - DH_REPO="cloudsuite/twitter-dataset-graph" IMG_TAG="latest" DF_PATH="./datasets/twitter-dataset-graph"

  
  # Benchmark Images
  # Data Analytics
  - DH_REPO="cloudsuite/data-analytics" IMG_TAG="3.0" DF_PATH="./benchmarks/data-analytics/3.0"
  - DH_REPO="cloudsuite/data-analytics" IMG_TAG="4.0" DF_PATH="./benchmarks/data-analytics/4.0" IMG_LATEST_TAG="latest"

  # Data Caching
  - DH_REPO="cloudsuite/data-caching" IMG_TAG="server-v3" DF_PATH="./benchmarks/data-caching/server-v3"
  - DH_REPO="cloudsuite/data-caching" IMG_TAG="client-v3" DF_PATH="./benchmarks/data-caching/client-v3"
  - DH_REPO="cloudsuite/data-caching" IMG_TAG="server-v4" DF_PATH="./benchmarks/data-caching/server-v4" IMG_LATEST_TAG="server"
  - DH_REPO="cloudsuite/data-caching" IMG_TAG="client-v4" DF_PATH="./benchmarks/data-caching/client-v4" IMG_LATEST_TAG="client"

  # Data Serving
  - DH_REPO="cloudsuite/data-serving" IMG_TAG="server-v3" DF_PATH="./benchmarks/data-serving/server-v3"
  - DH_REPO="cloudsuite/data-serving" IMG_TAG="client-v3" DF_PATH="./benchmarks/data-serving/client-v3"
  - DH_REPO="cloudsuite/data-serving" IMG_TAG="server-v4" DF_PATH="./benchmarks/data-serving/server-v4" IMG_LATEST_TAG="server"
  - DH_REPO="cloudsuite/data-serving" IMG_TAG="client-v4" DF_PATH="./benchmarks/data-serving/client-v4" IMG_LATEST_TAG="client"

  # Graph Analytics
  - DH_REPO="cloudsuite/graph-analytics" IMG_TAG="3.0" DF_PATH="./benchmarks/graph-analytics/3.0"
  - DH_REPO="cloudsuite/graph-analytics" IMG_TAG="4.0" DF_PATH="./benchmarks/graph-analytics/4.0" IMG_LATEST_TAG="latest"

  # In-memory Analytics
  - DH_REPO="cloudsuite/in-memory-analytics" IMG_TAG="latest" DF_PATH="./benchmarks/in-memory-analytics/3.0"
  - DH_REPO="cloudsuite/in-memory-analytics" IMG_TAG="4.0" DF_PATH="./benchmarks/in-memory-analytics/4.0" IMG_LATEST_TAG="latest"

  # Media Streaming
  - DH_REPO="cloudsuite/media-streaming" IMG_TAG="client-v3" DF_PATH="./benchmarks/media-streaming/client-v3"
  - DH_REPO="cloudsuite/media-streaming" IMG_TAG="server-v3" DF_PATH="./benchmarks/media-streaming/server-v3"
  - DH_REPO="cloudsuite/media-streaming" IMG_TAG="dataset-v3" DF_PATH="./benchmarks/media-streaming/dataset-v3"
  - DH_REPO="cloudsuite/media-streaming" IMG_TAG="client-v4" DF_PATH="./benchmarks/media-streaming/client-v4"	IMG_LATEST_TAG="client"
  - DH_REPO="cloudsuite/media-streaming" IMG_TAG="server-v4" DF_PATH="./benchmarks/media-streaming/server-v4"	IMG_LATEST_TAG="server"
  - DH_REPO="cloudsuite/media-streaming" IMG_TAG="dataset-v4" DF_PATH="./benchmarks/media-streaming/dataset-v4"	IMG_LATEST_TAG="dataset"


  # Web Search
  - DH_REPO="cloudsuite/web-search" IMG_TAG="server-v3" DF_PATH="./benchmarks/web-search/server-v3"
  - DH_REPO="cloudsuite/web-search" IMG_TAG="client-v3" DF_PATH="./benchmarks/web-search/client-v3"
  - DH_REPO="cloudsuite/web-search" IMG_TAG="server-v4" DF_PATH="./benchmarks/web-search/server-v4" IMG_LATEST_TAG="server"
  - DH_REPO="cloudsuite/web-search" IMG_TAG="client-v4" DF_PATH="./benchmarks/web-search/client-v4" IMG_LATEST_TAG="client"

  # Web Serving
  - DH_REPO="cloudsuite/web-serving" IMG_TAG="db_server-v3" DF_PATH="./benchmarks/web-serving/db_server-v3"
  - DH_REPO="cloudsuite/web-serving" IMG_TAG="faban_client-v3" DF_PATH="./benchmarks/web-serving/faban_client-v3"
  - DH_REPO="cloudsuite/web-serving" IMG_TAG="web_server-v3" DF_PATH="./benchmarks/web-serving/web_server-v3"
  - DH_REPO="cloudsuite/web-serving" IMG_TAG="memcached_server-v3" DF_PATH="./benchmarks/web-serving/memcached_server-v3"
  - DH_REPO="cloudsuite/web-serving" IMG_TAG="db_server-v4" DF_PATH="./benchmarks/web-serving/db_server-v4"			IMG_LATEST_TAG="db_server"
  - DH_REPO="cloudsuite/web-serving" IMG_TAG="faban_client-v4" DF_PATH="./benchmarks/web-serving/faban_client-v4"		IMG_LATEST_TAG="faban_client"
  - DH_REPO="cloudsuite/web-serving" IMG_TAG="web_server-v4" DF_PATH="./benchmarks/web-serving/web_server-v4"			IMG_LATEST_TAG="web_server"
  - DH_REPO="cloudsuite/web-serving" IMG_TAG="memcached_server-v4" DF_PATH="./benchmarks/web-serving/memcached_server-v4	IMG_LATEST_TAG="memcached_server"


  #Spell Check
  - Spell_Check="1"

# Separate build for spellcheck in modified .md files and auto-updation of gh-pages branch
script:
  - if [[ -z $Spell_Check ]];
    then source ${TRAVIS_BUILD_DIR}/scripts/travis/travis.sh;
    else source ${TRAVIS_BUILD_DIR}/scripts/travis/docs.sh;
    fi
